"""empty message

Revision ID: 305a8a2534c5
Revises: 5d62a24017d4
Create Date: 2025-04-26 16:26:30.315564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305a8a2534c5'
down_revision = '5d62a24017d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_timeslot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('create_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DATETIME(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    op.drop_table('weekly_timeslot')
    # ### end Alembic commands ###
