"""Add course_id with constraint name to enrollment

Revision ID: 4272f598e015
Revises: cd1ba88a1c0a
Create Date: 2025-05-13 14:55:58.474047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4272f598e015'
down_revision = 'cd1ba88a1c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_enrollment_course_id', 'course', ['course_id'], ['id'])

    with op.batch_alter_table('front_user', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('avatar')
        batch_op.drop_column('signature')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('front_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=6), nullable=True))

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_enrollment_course_id', type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
