"""empty message

Revision ID: 50eaf5d853e3
Revises: 305a8a2534c5
Create Date: 2025-04-26 16:49:12.098751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50eaf5d853e3'
down_revision = '305a8a2534c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('timeslot_id', sa.Integer(), nullable=False),
    sa.Column('enroll_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['timeslot_id'], ['weekly_timeslot.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['front_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment')
    # ### end Alembic commands ###
