"""empty message

Revision ID: 6cb432140294
Revises: 50eaf5d853e3
Create Date: 2025-05-06 14:05:28.588280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb432140294'
down_revision = '50eaf5d853e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_timeslot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_hour', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('duration_hours', sa.Integer(), nullable=False))
        batch_op.drop_column('hour')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_timeslot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hour', sa.INTEGER(), nullable=False))
        batch_op.drop_column('duration_hours')
        batch_op.drop_column('start_hour')

    # ### end Alembic commands ###
