"""empty message

Revision ID: 9e9bde06c43a
Revises: 18d545148818
Create Date: 2025-04-21 21:08:46.176244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9bde06c43a'
down_revision = '18d545148818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('student')
    op.drop_table('group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('group_name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('student',
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.drop_table('cms_user')
    # ### end Alembic commands ###
