"""empty message

Revision ID: d263092639bc
Revises: 4272f598e015
Create Date: 2025-05-13 15:11:37.020831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd263092639bc'
down_revision = '4272f598e015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('timeslot_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('timeslot_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
